"""Central configuration for the Smart Advisor MVP.

This module contains shared paths and column names. It does not include
business logic, model loading, training, prediction, or Streamlit code.
"""

from pathlib import Path


# Project paths
BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
MODELS_DIR = BASE_DIR / "models"


# Data and model artifacts
DATASET_PATH = DATA_DIR / "dataset.csv"
MODEL_PATH = MODELS_DIR / "model.pkl"
FEATURE_COLUMNS_PATH = MODELS_DIR / "feature_columns.pkl"
MODEL_PACKAGE_PATH = MODELS_DIR / "best_rf_model_package.pkl"


# Dataset columns
PRICE_COLUMN = "PRICE"
TARGET_COLUMN = "LOG_PRICE"
NEIGHBORHOOD_COLUMN = "LOCATIONNAME"
UNIT_PRICE_COLUMN = "UNITPRICE"
AREA_COLUMN = "CONSTRUCTEDAREA"
LOG_AREA_COLUMN = "LOG_CONSTRUCTEDAREA"
ROOMS_COLUMN = "ROOMNUMBER"
BATHROOMS_COLUMN = "BATHNUMBER"
HAS_TERRACE_COLUMN = "HASTERRACE"
HAS_LIFT_COLUMN = "HASLIFT"
HAS_AIR_CONDITIONING_COLUMN = "HASAIRCONDITIONING"
HAS_PARKING_COLUMN = "HASPARKINGSPACE"
HAS_BOXROOM_COLUMN = "HASBOXROOM"
HAS_SWIMMING_POOL_COLUMN = "HASSWIMMINGPOOL"
DISTANCE_TO_CITY_CENTER_COLUMN = "DISTANCE_TO_CITY_CENTER"
DISTANCE_TO_CASTELLANA_COLUMN = "DISTANCE_TO_CASTELLANA"
DISTANCE_TO_METRO_COLUMN = "DISTANCE_TO_METRO"
MEAN_UNITPRICE_BY_LOCATION_COLUMN = "MEAN_UNITPRICE_BY_LOCATION"


# Definitive model input contract. User-facing columns are entered in the app;
# engineered and neighborhood-derived columns are calculated automatically.
USER_INPUT_FEATURE_COLUMNS = [
    NEIGHBORHOOD_COLUMN,
    AREA_COLUMN,
    ROOMS_COLUMN,
    BATHROOMS_COLUMN,
    HAS_TERRACE_COLUMN,
    HAS_LIFT_COLUMN,
    HAS_AIR_CONDITIONING_COLUMN,
    HAS_PARKING_COLUMN,
    HAS_BOXROOM_COLUMN,
    HAS_SWIMMING_POOL_COLUMN,
]

BOOLEAN_FEATURE_COLUMNS = [
    HAS_TERRACE_COLUMN,
    HAS_LIFT_COLUMN,
    HAS_AIR_CONDITIONING_COLUMN,
    HAS_PARKING_COLUMN,
    HAS_BOXROOM_COLUMN,
    HAS_SWIMMING_POOL_COLUMN,
]

NEIGHBORHOOD_DERIVED_FEATURE_COLUMNS = [
    DISTANCE_TO_CITY_CENTER_COLUMN,
    DISTANCE_TO_CASTELLANA_COLUMN,
    DISTANCE_TO_METRO_COLUMN,
    MEAN_UNITPRICE_BY_LOCATION_COLUMN,
]

MODEL_FEATURE_COLUMNS = [
    LOG_AREA_COLUMN,
    ROOMS_COLUMN,
    BATHROOMS_COLUMN,
    HAS_TERRACE_COLUMN,
    HAS_LIFT_COLUMN,
    HAS_AIR_CONDITIONING_COLUMN,
    HAS_PARKING_COLUMN,
    HAS_BOXROOM_COLUMN,
    HAS_SWIMMING_POOL_COLUMN,
    DISTANCE_TO_CITY_CENTER_COLUMN,
    DISTANCE_TO_CASTELLANA_COLUMN,
    DISTANCE_TO_METRO_COLUMN,
    MEAN_UNITPRICE_BY_LOCATION_COLUMN,
]

# Backwards-compatible alias used by the provisional training script.
MVP_FEATURE_COLUMNS = USER_INPUT_FEATURE_COLUMNS


# Training configuration
RANDOM_STATE = 42
N_ESTIMATORS = 100
